apiVersion: v1
kind: Service
metadata:
  name: ct-monitor
  namespace: recon
  labels:
    app: ct-monitor
    component: monitoring
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8002
    targetPort: 8002
    protocol: TCP
  selector:
    app: ct-monitor

