apiVersion: v1
kind: Service
metadata:
  name: event-handler
  labels:
    app: event-handler
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app: event-handler
