apiVersion: v1
kind: Service
metadata:
  name: certstream
  labels:
    app: certstream-server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 4000
    targetPort: http
    protocol: TCP
  selector:
    app: certstream-server
