apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  labels:
    app: reconhawx
    component: config
data:
  # Service URLs
  api.url: "http://api:8000"
  frontend.url: "http://frontend:80"
  nats.url: "nats://nats:4222"
  redis.url: "redis://redis:6379/0"

  # Application Configuration
  service.port: "8000"
  job.ttl: "86400"
  access.token.expire.minutes: "15"
  refresh.token.expire.days: "30"

  # Kubernetes Configuration
  kubernetes.namespace: "reconhawx"
  runner.serviceaccount: "runner-service-account"
  runner.image: "ghcr.io/h3xitsec/reconhawx/runner:latest"
  worker.image: "ghcr.io/h3xitsec/reconhawx/worker:latest"
  image.pull.policy: "Always"

  # Runner configuration
  ## Typosquat caching configuration
  runner.typosquat.cache.ttl: "2592000"
  runner.typosquat.use.cache: "true"
  
  # Database
  database.name: "reconhawx"