{
 "title": "Workflow Logs",
 "tags": [ "reconhawx" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "workflow_id",
    "label": "Workflow ID",
    "query": {}
   },
   {
    "name": "workers",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Runner Log",
   "type": "logs",
   "gridPos": { "h": 34, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{app=\"workflow-runner\", workflow_id=\"$workflow_id\"} |= ``"
    }
   ]
  },
  {
   "title": "Workers Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(\n  sum by (pod) (\n    count_over_time({pod=~\"$workers\", workflow_id=\"$workflow_id\"}[$__auto])\n  )\n)"
    }
   ]
  },
  {
   "title": "$workers",
   "type": "logs",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 4 },
   "repeat": "workers",
   "targets": [
    {
     "direction": "forward",
     "expr": "{app=\"worker\", workflow_id=\"$workflow_id\", pod=\"$workers\"} |= ``"
    }
   ]
  }
 ]
}