[tool:pytest]
asyncio_mode = auto
markers =
    asyncio: marks tests as async (deactivate with '-m "not asyncio"')
    integration: marks tests as integration tests
    performance: marks tests as performance tests
